services:
  - type: web
    name: campainha-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://campainha-digital.netlify.app
      - key: ABACATE_API_KEY
        sync: false
      - key: ABACATE_WEBHOOK_SECRET
        sync: false
