services:
  - type: web
    name: campainha-backend
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001

      - key: ABACATE_API_KEY
        sync: false
      - key: ABACATE_WEBHOOK_SECRET
        sync: false
